### ISSUE TITLE
Installation instructions issue

### ISSUE THREAD

**Issue by TotallyInformation** [Steveorevo/node-red-contrib-string#1]
"Run the following command in the root directory of your Node-RED install"

Should be "Run the following command in the user directory of your Node-RED install"

You shouldn't install nodes as the root user unless you really have to and Node-RED should never need that.

**Comment by Steveorevo** [comment]
You are correct! Updated in https://github.com/Steveorevo/node-red-contrib-string/commit/1fb9a5321a86ed1325f6db98341c1c380903682d

**Comment by TotallyInformation** [comment]
Cheers.
