### ISSUE TITLE
In OSX, nothing is showing in the methods section

### ISSUE THREAD

**Issue by juggledad** [Steveorevo/node-red-contrib-string#2]
8 Dec 06:59:41 - [info] Node-RED version: v0.17.5
8 Dec 06:59:41 - [info] Node.js  version: v6.11.0
8 Dec 06:59:41 - [info] Darwin 16.7.0 x64 LE
 
After installing the node, and opening an occurrence there is nothing in the Methods section, it is blank
![screen shot 2017-12-08 at 7 04 29 am](https://user-images.githubusercontent.com/11473405/33765803-a6ea80c2-dbe8-11e7-946c-7952a45146dd.png)

**Comment by Steveorevo** [comment]
It doesn't look like you've added any methods. The string object will not do anything until you start assigning methods to it. To assign a method, click the "+add" button and select the methods you wish to execute.

**Comment by juggledad** [comment]
Ummm...oh that is so simple once you know what to do. 

Since I couldn't figure that out, might I suggest you add - just before the examples - something like:

The **Methods** section will be empty when first installed. To add methods, press the small **+add** button at the bottom of the **Methods** section.
