### ISSUE TITLE
decodeURIComponent producing "URIError: URI malformed"

### ISSUE THREAD

**Issue by michaelblight** [Steveorevo/node-red-contrib-string#3]
I'm trying to decode "70%20%", which some tools correctly recognise as "70 %", but others fail to decode, like this does. I have a workaround, but it would be good to have it cope.

I have an IFTTT applet calling Bluemix with a webhook. When I speak "70 %" to my Google Home, and it gets passed through IFTTT to Node-Red, it arrives as "70%20%", so I'm guessing that IFTTT's encode is causing the problem.

A sample flow showing the problem:

`[{"id":"4d881eee.0ad06","type":"string","z":"f6747993.c9b448","name":"","methods":[{"name":"decodeURIComponent","params":[]}],"prop":"payload","propout":"payload","object":"msg","objectout":"msg","x":340,"y":460,"wires":[["bd547a18.09bc38"]]},{"id":"8ff76890.de6ce8","type":"inject","z":"f6747993.c9b448","name":"","topic":"","payload":"70%20%","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":460,"wires":[["4d881eee.0ad06"]]},{"id":"bd547a18.09bc38","type":"debug","z":"f6747993.c9b448","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":500,"y":460,"wires":[]}]`

**Comment by Steveorevo** [comment]
Interesting. In your experience, is this anomaly only with "70 %"; or have you encountered other interpretations where whitespace is overlooked?
