### ISSUE TITLE
Extract each indivisible characters from a string.

### ISSUE THREAD

**Issue by nodecentral** [Steveorevo/node-red-contrib-string#4]
Hi,

Using node-red  I have extracted a 15 digit string "100121001000111" that I need to break out /mdiwn individually I order to translate each one, as each byte means something.

So farm I can’t take the furthest left or right character, but I can seem to work out how to take the the 2nd or 3rd from left or fourth or fifth  from right etc.?

**Comment by Steveorevo** [comment]
It looks like you are trying to obtain a byte (8 ones or zeros) from the 15 digit string? But two bytes would actually be 16 digits not 15. Also, I see a '2' in "100121001000111". This does not look like a two byte value. 

If you want the left or right parts of a the string, you should be able to use the methods for ["left"](https://github.com/Steveorevo/string.js#--leftn) and ["right"](https://github.com/Steveorevo/string.js#--rightn).

For example in JavaScript:

var x = "0000000100000010"; // Contains bytes "1" and "2"
var a = x.left(8).
var b = x.right(8); 
a = parseInt(a, 2); // Now, a = 1
b = parseInt(b, 2); // Now b = 2

In NodeRED:

<img width="659" alt="screen shot 2018-09-15 at 11 50 46 pm" src="https://user-images.githubusercontent.com/635399/45593778-53389f80-b942-11e8-9319-8300702ebc75.png">

**Comment by nodecentral** [comment]
Sorry for not using the right terminology- each value in that 15 character string means something on a 4x4 HDMI Matrix

the first 4 characters tell me if a cable is connected to  each of the 4 inputs (a 1 = plugged in a 0 = no

**Comment by nodecentral** [comment]
I think I’ve found a way to do it.

If I use the right trim option to capture x number of characters from the right first, I can then pass that payload through another node, that this time just takes  the1 character from the left.

This looks like it will allow me to extract each character individually.
