### ISSUE TITLE
GetxxxxMost, DelxxxMost without losing searched keyword

### ISSUE THREAD

**Issue by ipa64** [Steveorevo/node-red-contrib-string#5]
Hi,
Thanks for your useful node !
I don’t think it’s a bug, but rather a request.
I have noticed that all these commands DelLeftMost, DelRightMode, GetRightMode, GetLeftMode will lose the searched keyword.

Here a portion of my sample to _parse :
..."_Sleep":50,"LoadAvg":19,"POWER1":"ON","POWER2":"OFF","POWER3":"ON","POWER4":"OFF","Wifi":"mywifi_" ...._

At first I would like to extract this part : POWER1":"ON","POWER2":"OFF","POWER3":"ON","POWER4":"OFF"

The problem:
If I use command like DelLeftMost POWER, because the searched keyword is lost I get this : 
1":"ON","POWER2":"OFF","POWER3":"ON","POWER4":"OFF","Wifi":...
For the right part in this case that’s ok to lose the keyword DelRigthMost Wifi 
Note that the string haven’t a fixed length, so I cannot extract just a length.

I think I have tried all commands without success, but maybe I have missed something 

Thank you

I have tried a lot of commands available without success but maybe I have missed something

**Comment by Steveorevo** [comment]
Use the prepend and append methods to include the keyword.

**Comment by ipa64** [comment]
Ok thank you
