### ISSUE TITLE
When using Length I get an error

### ISSUE THREAD

**Issue by marksmanaz** [Steveorevo/node-red-contrib-string#6]
To get the length of a string I get this error.

TypeError: context[func].apply is not a function

**Comment by Steveorevo** [comment]
Fixed in latest commit; will be included in next release. 

https://github.com/Steveorevo/node-red-contrib-string/commit/c82a9ea99603d1a1776d49fc503a0a710183da16#diff-0d8a13f46c1e2387c320b90b7f097a6b6c992baf39aba4b2e5edd2321ccc0a9a
