### ISSUE TITLE
Cases

### ISSUE THREAD

**Issue by PierreScerri** [Steveorevo/node-red-contrib-string#7]
Is it possible to have other CASE options like upper case, lower case and title case?

Thank you.

**Comment by Steveorevo** [comment]
Upper and Lower is certainly doable; note that Title case should  currently be available; is it missing from your dialog? Supported methods should mirror: 

https://github.com/Steveorevo/string.js

**Comment by PierreScerri** [comment]
Capitalise is there but that is not the same.  It only capitalises the first letter.

**Comment by Steveorevo** [comment]
titleCase() is apart of the API. May only be accessible in scripting; can be added to UI. 

Returns a string with the first letter of each word uppercased, including hyphenated words

**Comment by Steveorevo** [comment]
titleCase, toUpperCase, toLowerCase, and a bug fix for length has been added to the latest release (v. 1.0.0).

**Comment by PierreScerri** [comment]
That is super.  Well done.  Thank you.
