### ISSUE TITLE
Wrong link?

### ISSUE THREAD

**Issue by Just-another-pleb** [Steveorevo/node-red-contrib-string#9]
In your documentation the link to `stringjs.com` is mentioned.

I don't think it is still valid.

**Comment by Steveorevo** [comment]
Yup. It looks like the project was abandoned. Note that this project uses a fork under my account. A PR was requested but the original author is not responding.

**Comment by Just-another-pleb** [comment]
No problems.   Just wasn't sure if you knew and/or if it is that important.
